### ISSUE TITLE
Provide basic interfaces for autoupdating

### ISSUE THREAD

**Issue by xiam** [getlantern/autoupdate#1]
Looks like we can use https://github.com/inconshreveable/go-update to download and apply binary patches to update lantern tools. Before rushing to implement go-update we should also define a general interface, more specific to lantern, just in case we ever need to change or extend the auto-update backend.

Related: https://github.com/getlantern/lantern/issues/21

**Comment by oxtoacart** [comment]
@xiam and @myleshorton how do you feel about going ahead and using equinox.io for this?

**Comment by xiam** [comment]
@oxtoacart I think that's a good idea, it would allow us to deliver quickly. Let's try that first. Before start coding I'd like to describe and discuss the general idea behind go-update (+ equinox?) and how could we apply that to lantern. I'm currently working on this description and will share it with you soon.

**Comment by oxtoacart** [comment]
@xiam that sounds great.

**Comment by xiam** [comment]
Hello @oxtoacart, @myleshorton,

Here's the proposal I was working on:

https://github.com/getlantern/autoupdate/tree/feature/general-design

I've also drafted the interfaces a tool like this should satisfy:
 https://github.com/getlantern/autoupdate/blob/feature/general-design/interfaces.go

The only interaction the Lantern program will do is to set its internal release number (with `SetVersion()`) and then call `Do()` which will (atomically) apply a patch, when available.

Now, I've also checked `go-update` and equinox as possible auto-update backend but I'm concerned about the safety/integrity of the binary diffs, in fact the a binary diff is never signed (and this is OK, because we're the only party that is supposed to hold the signing private key).

See this note from the `go-update` source code:

```
You should also verify the checksum of new updates as well as verify
the digital signature of an update. Note that even when you choose to apply
a patch, the checksum is verified against the complete update after that patch
has been applied.
    up := update.New().ApplyPatch(update.PATCHTYPE_BSDIFF).VerifyChecksum(checksum)
    err, errRecover := up.FromUrl("http://release.example.com/2.0/mypatch")
```

I _think_ this can be safe enough, checking the signature after applying the patch but before renaming the binary should also guarantee its integrity. My proposal was signing the binary diff before sending it and checking it before attempting to patch anything, but that would require a custom server that holds our private keys for signing the diffs and it would take us more time so I guess we can just go and use equinox.

Besides that detail, I think we could use equinox and `go-update`, provided that we create our own controller fork of `go-update` and that we sign every release.

Can you help me reviewing the proposal? Did you noticed anything that may cause us problem in the future?

**Comment by oxtoacart** [comment]
Nice start!  Some thoughts (in no particular order).

### Proxied vs Direct Requests

We should proxy everything (don't bother trying unproxied request first).  There are several reasons for this:
1. When censors interfere with connections, they can do so in a variety of ways.  Sometimes they disconnect the connection entirely, sometimes they disconnect it only after a while, sometimes they may even just throttle it.  So the initial download may take some time before it fails, or fail in a non-obvious way.
2. When the censors (in particular China) observe an IP attempting to access blocked content, they will sometimes punish that IP by blocking all access from that IP for some period of time (I think it's on the order of half an hour to several hours, but I'm not 100% sure about the duration).
3. In theory, if the censors see a machine attempting to download a Lantern patch, they can then observe subsequent traffic from that machine and use it to identify IPs that may be acting as proxies, which they can then port scan and shut down if they decide to do so.

We should assume that any and all of our infrastructure is blocked and being monitored, so we should always access it through proxies.  This applies to the config updates that you're downloading with lantern-android too.

### Signatures

Verifying the signature on the patched binary rather than the patch itself should be fine.  I'll add that even if we don't do binary patches at first, we will still want to verify the signature of the patched binary.  Given the potential combinations of current and upgrade versions of Lantern, there are a lot of potential patches.  Presumably equinox generates these on-demand based on the checksum of the current version and the latest released version.  If we implemented a server that works similarly, our server would have to have the signing key for signing the patches--I would prefer that we don't keep that key on any servers.  So even if we did it ourselves, I don't think the patches would be signed.

One thing that I don't understand about go-update and equinox is exactly what kind of signatures they require, and whether these are compatible with the signatures that the operating systems (Windows and OS X) require.  We already sign our binaries using [mechanisms](https://github.com/getlantern/flashlight-build/blob/devel/copyexecutables.bash) specific to those operating systems, which we have to continue to do to make sure their firewalls are happy, etc.

### Update Experience

We need to figure out what the user's experience is.  Do we immediately install the update?  If so, what happens if the user is currently using Lantern to proxy traffic?  What if the user is currently looking at the Lantern UI?  Also, the Lantern UI is web-based and could be open in a browser window while we do the update.  If we don't refresh the UI, we'll have an old version of the UI pointing at a new version of the back-end.  Do we need to force a refresh on auto-update?

I think that our approach to handling the update experience will have a big impact on the final interface for the auto-update API.

**Comment by xiam** [comment]
Hello @oxtoacart!

> We should proxy everything (don't bother trying unproxied request first).

Woah! The Internet's a tricky place, and that sucks. That was very informative, you're right, even the innocent intention of downloading a binary patch could put other people at risk. I'll take this in account for lantern-android too.

> One thing that I don't understand about go-update and equinox is exactly what kind of signatures they require.

The current `go-update` implementation finishes when the binary has been replaced and the checksum has been verified. According to the source, they're using [RSA Standard](http://golang.org/pkg/crypto/rsa/#VerifyPKCS1v15).

> and whether these are compatible with the signatures that the operating systems (Windows and OS X) require. 

It should not not affect any properties of the binary itself as the signature does not alter the target binary at all.

> Presumably equinox generates these on-demand based on the checksum of the current version and the latest released version. 

As far as I understand, you're correct.

> If we implemented a server that works similarly, our server would have to have the signing key for signing the patches

Yeah, a way to handle this signing key without actually printing it on the program's source would be feeding it to the server when the program starts, but that would be inconvenient and would require human intervention.

One last point, the equinox server is a black box, it's not open-source and we can't tell how does it work for sure so we'll be depending on it, using public key cryptography and signed releases would protect our users in case equinox gets compromised and our binaries are modified or changed, but still, as a central distribution server it can be DoSed and that would affect our users. 

> We need to figure out what the user's experience is.

Some suggestions:
- Make auto-updating the default behaviour, I think auto-updates are a very convenient way to distribute security or high priority patches. An user may turn them on/off anytime.
- We should wait some days before rolling a release to equinox after the actual new version release, we need to be absolutely sure there's nothing wrong with the updates we'll be pushing.
- I think no more work is required in the UI, besides a checkbox that turns updates on/off, that would make things easier on the UI programming side and less complicated for users. We may also require a message that suggest the user that a new release is available and they must restart the program (or programs) to complete the upgrade.

## Let's continue!

I'll start satisfying the interfaces I proposed using go-update + equinox as our current backend and also documenting everything we need to know in order to push a release, I think if any change is required we'll be able to do it easily if we think on the interfaces rather than on the implementation.

**Comment by oxtoacart** [comment]
> I think no more work is required in the UI, besides a checkbox that turns updates on/off, that would make things easier on the UI programming side and less complicated for users.

I don't think auto-updates should be optional for users, so I would skip configuration option.  I think for developers though we should have a command-line flag that allows disabling it so that we don't get auto-updated in the middle of testing our own changes!

> We may also require a message that suggest the user that a new release is available and they must restart the program (or programs) to complete the upgrade.

The problem with this is that Lantern is really meant to run all the time.  So, if the user doesn't restart Lantern and the user doesn't reboot her machine, the update will never get applied.  We want to be really aggressive about applying updates, so I think we need to figure out something else here.

As an MVP solution, I think it would be sufficient to simply restart Lantern as soon as the update is in place.  This may interrupt a page load or in the worst case a download, but to be honest we've been having enough unreliability in our infrastructure lately that this is unlikely to stand out, especially when you consider that we route some percentage of traffic through domain-fronted peers which are generally quite unreliable.

Longer term, I don't think it would be very hard to implement a [zero-downtime restart](http://blog.nella.org/?p=879), perhaps using [goagain](https://github.com/rcrowley/goagain).

Also, I do think we need to solve the issue of refreshing the UI.  One way to accomplish this would be to have the UI track which version of Lantern it was loaded from.  When the UI detects that the backend is running a different version, it can reload itself.  This seems like a nice way to enforce the invariant that the UI is always on the same version of code as the back-end, which is important to avoid people reporting bugs that arise due to a mismatch, which we will have no hope of reproducing.

**Comment by myleshorton** [comment]
Yeah agreed on all of that @oxtoacart. One simple way we could encourage the user to update the app would be to change the system tray icon to red or something like that indicate user-action is required.

By far the most challenging part of this to me is the digital signatures. It at least appears that when go-update/equinox applies an update it both applies the update to the main executable as well as updates the signature according to the requirements on each platform. Does that appear to be the case @xiam?

**Comment by xiam** [comment]
@myleshorton  I'm wondering if the code signing process you're talking about will interfere with the binary patches, does it encrypt the binary file? I'll need to investigate it, if a significative portion of the executable is changed after signing we'll need to do some extra work to actually use binary diffs. The actual signing you're referring to is done in [copyexecutables.bash](https://github.com/getlantern/flashlight-build/blob/devel/copyexecutables.bash), right?

Currently, go-update takes the actual bytes of the executable file and generates a RSA signature but it does not change the executable file at all.

It would be really useful if you could check this [example program](https://github.com/getlantern/autoupdate/blob/master/_test_app/main.go) that is supposed to be updated using our `autoupdate` package, I think it has everything we need to silently update the package and to alert the application its executable file has been updated.  I've also posted [instructions](https://github.com/getlantern/autoupdate/tree/master/_test_app) on how to use the equinox platform for releasing updates.

**Comment by xiam** [comment]
@oxtoacart 

> As an MVP solution, I think it would be sufficient to simply restart Lantern as soon as the update is in place.

I agree on this (for the MVP). A message will be sent to a channel `UpdatedTo` when a patch has been applied and that message can be used for the program to restart itself.

I don't know how will the UI tell if the backend is running a newer version, I think the backend could send the UI a signal each time it starts or when it receives an update?

I've following the discussion on the hypervisor proposal (for the long term), I really like it.

**Comment by myleshorton** [comment]
> @myleshorton I'm wondering if the code signing process you're talking about will interfere with the binary patches, does it encrypt the binary file? 

It doesn't encrypt the binary file (it basically encrypts the hash of the file with your private key), but I share your concern. Basically each platform handles this a bit differently, and at the end of the day what's on the user's machine needs to match the expected format/packaging for how that platform handles code signing. 

I'm worried that go-update uses a generic code signing mechanism that doesn't conform to those platform-specific requirements, but I would just try it and see starting with either Windows or OSX. Here's an overview of what happens on OSX and Windows:

https://developer.apple.com/library/mac/technotes/tn2206/_index.html
https://msdn.microsoft.com/en-us/library/ie/ms537361(v=vs.85).aspx

> I'll need to investigate it, if a significative portion of the executable is changed after signing we'll need to do some extra work to actually use binary diffs. 

The executable itself doesn't change, but the packaging can (app bundle on OSX - I'm not entirely clear on how Windows handles it honestly, and it's not an issue on Ubuntu because we don't sign stuff.) 

> The actual signing you're referring to is done in copyexecutables.bash, right?

Yeah.

> It would be really useful if you could check this example program that is supposed to be updated using our autoupdate package, I think it has everything we need to silently update the package and to alert the application its executable file has been updated. I've also posted instructions on how to use the equinox platform for releasing updates.

I'll have a look!

**Comment by oxtoacart** [comment]
> The executable itself doesn't change, but the packaging can (app bundle on OSX - I'm not entirely clear on how Windows handles it honestly, and it's not an issue on Ubuntu because we don't sign stuff.)

Actually, on OS X, we sign the executable itself.  We may also sign the App bundle (I don't know, that's Install4J's responsibility), but the executable is definitely modified.  It's not clear whether go-update's signing mechanism would interfere with that, we just have to test it.

On Windows, per the link that you sent, if we're using the portable executable image file format (which I think we are), then "the PKCS #7 signature file contents are stored in the binary file itself, in an additional section".  It's not entirely whether go-update's signing mechanism would interfere with that, again just need to test it.

Keep in mind too that we don't need to use go-update's signing mechanism if we don't want to.  In theory,  we should be able to verify the signature ourselves if we want to.  In terms of working with portable executable files, it looks like golang actually provides a package for working with those - http://godoc.org/debug/pe.  For Mac, we could actually just use the codesign command-line program with the -s and -R flags.  For info about sepcifying requirements - https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/RequirementLang/RequirementLang.html.

**Comment by oxtoacart** [comment]
BTW, Adam mentioned a concern about signing of App Bundles on OS X and replacing the executable.  I just did a test where I installed Lantern (which has a signed app bundle), then replaced the executable in the installed app bundle with another unsigned executable, and the app still started up okay without prompting the user.  So I think we're good there.

**Comment by oxtoacart** [comment]
So, I finally installed the equinox tool. It's actually quite annoying. In particular, it seems to insist on doing the compilation for me and then immediately uploads the binary, without giving me a chance to do the native code signing. So, I'm not sure how we'll make it work.

**Comment by xiam** [comment]
@oxtoacart 

>  It seems to insist on doing the compilation for me and then immediately uploads the binary, without giving me a chance to do the native code signing. So, I'm not sure how we'll make it work.

Also it's closed source software so we can't just fix it. The equinox's documentation mention a REST API we could use to roll our own releases but that is actually not documented anywhere.

I think we should ask the equinox team to release the API docs and create our own upload tool (that already does the code signing we need).

**Comment by myleshorton** [comment]
Hey I just realized @xiam that we normally try to put all of the issues in getlantern/lantern just so they're all in one place. I just referenced this from https://github.com/getlantern/lantern/issues/21, so we're all good, but just FYI.

**Comment by xiam** [comment]
Thanks @myleshorton! If you don't mind I'll get back there when this package is ready to close the original issue.

Just a [quick note](https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html) from the Apple's Code Signing documentation:

> You can take a partial-update approach to revising your code on the user’s system. To do so, sign the new version as usual, then calculate the differences between the new and the old signed versions, and transmit the differences. Because the differences include the new signature data, the result of installing the changes on the end-user's system will be the newly signed version. You cannot patch a signed application in the field. If you do so, the system will notice that the application has changed and will invalidate the signature, and there is no way to re-validate or resign the application in the field.

So yes, as we supposed, we need to sign the binary before publishing it, at least for the OSX build.

The thing we need now is being able to build and sign the new release by ourselves, I'm already talking about that with the Equinox's author and I'm pretty confident we'll be able to test this out very soon.

**Comment by xiam** [comment]
> BTW, Adam mentioned a concern about signing of App Bundles on OS X and replacing the executable. I just did a test where I installed Lantern (which has a signed app bundle), then replaced the executable in the installed app bundle with another unsigned executable, and the app still started up okay without prompting the user. So I think we're good there.

That's was odd, the documentation says it is not enough to replace the executable with an unsigned new one in the same path; it must be signed by the same identity too, but it also says that some user-specific settings can prevent showing an alert when that happens, so I suppose that was why you're not getting a warning. According to the documentation, we'll have to sign all our binaries in the same fashion we've been doing it and the binary constructed based on the diff must also contain a valid signature.

I've ran a test on OSX and the signing does change the binary, of course, but it does not affect compression a lot:

``` sh
go build github.com/getlantern/flashlight
shasum flashlight
# f7afdf492d49c6d3f058e1da0873fd87d37ce774  flashlight
mv flashlight flashlight.original
go build github.com/getlantern/flashlight
codesign -s "Development" -f flashlight
shasum flashlight                                                                                                                                           
# d6471bbeac47490792b78e5d991e39fec170f295  flashlight
bsdiff flashlight.original flashlight flashlight.patch
du -h flashlight*
# 19M    flashlight
# 19M    flashlight.original
#100K    flashlight.patch
```

Now I'll start reviewing how are these things supposed to work on the Windows side of life.

**Comment by oxtoacart** [comment]
> That's was odd, the documentation says it is not enough to replace the executable with an unsigned new one in the same path; it must be signed by the same identity too, but it also says that some user-specific settings can prevent showing an alert when that happens, so I suppose that was why you're not getting a warning. According to the documentation, we'll have to sign all our binaries in the same fashion we've been doing it and the binary constructed based on the diff must also contain a valid signature.

You are correct.  My test assumed that our Lantern.app bundle is signed, but it's not.  When someone downloads lantern, they get a lantern-installer.dmg.  The lantern-installer.dmg contains a Lantern Installer.app, which is signed.

``` bash
➜  flbuild git:(valencia-mac) ✗ spctl --assess --verbose=4 -t execute /Applications/Lantern.app
/Applications/Lantern.app: rejected
source=no usable signature
➜  flbuild git:(valencia-mac) ✗ spctl --assess --verbose=4 -t install /Volumes/lantern/Lantern\ Installer.app
/Volumes/lantern/Lantern Installer.app: accepted
source=Developer ID
```

I guess having an app that came from a signed installer is good enough to allow it to execute without prompting the user, even if the app itself isn't signed.  The downside is that if someone replaces the executable, that'll run just fine too :(

In the new go-lantern, I will be signing the Lantern.app (and the binary inside of it) and distributing it in a dmg that follows the usual drag and drop convention for installing it in the Applications folder.

I tested that replacing the included executable with another one signed by the same identity works, and as you say, replacing it with an unsigned executable does not.

**Comment by xiam** [comment]
> In the new go-lantern, I will be signing the Lantern.app (and the binary inside of it) and distributing it in a dmg that follows the usual drag and drop convention for installing it in the Applications folder.

Sounds good Ox! With that in mind I think we won't have any issues with code signing and binary diffs.

I've just confirmed the Windows signatures also are tiny modifications that won't affect the binary diff too much:

``` sh
osslsigncode sign -pkcs12 authenticode.pfx -pass [redacted] -in _test_app_windows_amd64.exe -out _test_app_windows_amd64.exe.signed
bsdiff _test_app_windows_amd64.exe _test_app_windows_amd64.exe.signed _test_app_windows_amd64.exe.patch
du -h _test_app_windows_amd64.exe*
# 6.5M  _test_app_windows_amd64.exe
# 4.0K  _test_app_windows_amd64.exe.patch
# 6.5M  _test_app_windows_amd64.exe.signed
```

Let's keep going!

**Comment by xiam** [comment]
Documentation for the Equinox REST API is still missing so I sniffed the actual communications between the equinox tool and the equinox server and created a compatible client (signatures included). That was fun! With this I've confirmed our supposition: Equinox's signatures _do not_ affect code signing at all.

We'll still use the Equinox platform for now, but instead of the equinox tool we'll use this new tool and copyexecutables.bash.

More exciting stuff coming!

**Comment by xiam** [comment]
I've succeeded at releasing an applying an update for a codesigned binary for OSX using our new `releasetool` command, the binary updates itself and the OS signature is still in place. Everything looks good!

I've created an [autoupdate](https://github.com/getlantern/flashlight-build/tree/feature/autoupdate) branch in flashlight-build that can help up testing everything.

So I guess this issue can be closed. Let's continue discussing on https://github.com/getlantern/lantern/issues/21 how are we going to include this on Lantern :-).

**Comment by oxtoacart** [comment]
Awesome!  I'm looking forward to taking a look.

Cheers,
Ox

---

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."
- Marge Piercy

**Comment by myleshorton** [comment]
Very cool!
